### ISSUE TITLE
Value containing `{` or `}` won't able to pass via `$${1}`

### ISSUE THREAD

**Issue by charz** [open-telemetry/opentelemetry-collector#10613]
**Describe the bug**

I'm able to pass `$${1}` to value In v0.96.0, but it's not allow in v0.104.0 (maybe it was failed in the earlier version?). Is possible to add `{` and `}` in value?

```
$ ./otelcol-contrib --config=file:a.yaml --config=file:metric.yaml
Error: failed to resolve config: cannot resolve the configuration: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$
2024/07/15 12:20:14 collector server run finished with error: failed to resolve config: cannot resolve the configuration: environment variable "1" has invalid name: must match regex ^[a-zA-Z_][a-zA-Z0-9_]*$

$ ./otelcol-contrib --version
otelcol-contrib version 0.104.0

$ cat metric.yaml
processors:
  metricstransform:
    transforms:
      - include: ^([^s_].*)$
        match_type: regexp
        action: update
        new_name: "unknown_metric"
        operations:
          - action: add_label
            new_label: name
            new_value: "$${1}"
            
          
```

**Steps to reproduce**

Here is the configuration file, and just run `./otelcol-contrib --config=file:a.yaml --config=file:metric.yaml`
```
$ cat metric.yaml
processors:
  metricstransform:
    transforms:
      - include: ^([^s_].*)$
        match_type: regexp
        action: update
        new_name: "unknown_metric"
        operations:
          - action: add_label
            new_label: name
            new_value: "$${1}"
            
$ car a.yaml
receivers:
  statsd:
    endpoint: "127.0.0.1:8125" # default
    aggregation_interval: 15s  # default
    enable_simple_tags: true
    enable_metric_type: false
    is_monotonic_counter: true
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "histogram"
        histogram:
          max_size: 50
      - statsd_type: "timing"
        observer_type: "summary"
      - statsd_type: "distribution"
        observer_type: "histogram"
        histogram:
          max_size: 50

exporters:
  prometheus:
    endpoint: "0.0.0.0:9102"
    send_timestamps: false
    metric_expiration: 120m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true


processors:
  batch:


service:
  telemetry:
    logs:
      level: info
    metrics:
      address: ":8889"
  pipelines:
    metrics:
      receivers: [statsd]
      processors: [batch, metricstransform]
      exporters: [prometheus]
      
```

**What did you expect to see?**
The `$${1}` should able to pass to value.

**What did you see instead?**
It works in v0.96.0. 

**What version did you use?**
version: v0.104.0

**Environment**
OS: Mac
Compiler(if manually compiled): go 1.21

**Additional context**
None

**Comment by mx-psi** [comment]
Thanks for reporting! This was fixed by #10560 and will be released in the next version. On v0.104.0 and v0.103.0 you can disable the `confmap.unifyEnvVarExpansion` feature gate to work around this by passing the `--feature-gates=-confmap.unifyEnvVarExpansion` command line option.

Let me know if that makes sense to you, thanks!

**Comment by charz** [comment]
> Thanks for reporting! This was fixed by #10560 and will be released in the next version. On v0.104.0 and v0.103.0 you can disable the `confmap.unifyEnvVarExpansion` feature gate to work around this by passing the `--feature-gates=-confmap.unifyEnvVarExpansion` command line option.
> 
> Let me know if that makes sense to you, thanks!

Cool! thanks! I'll use `--feature-gates=-confmap.unifyEnvVarExpansion` for my current binary.

**Comment by mx-psi** [comment]
We believe this to be fixed in v0.105.0. If you still find issues related to this, please comment and I can reopen

**Comment by cloudchristina** [comment]
Hi @mx-psi I disabled the confmap.unifyEnvVarExpansion, however, still not working. May I ask if it works for you?

**Comment by mx-psi** [comment]
@cloudchristina what version of the Collector are you using?

**Comment by cloudchristina** [comment]
Hi @mx-psi I have tried v0.96.0, v0.104.0, v0.107.0

**Comment by TylerHelmuth** [comment]
@cloudchristina try v0.108.0, thats the latest version when the module is stable.

**Comment by TylerHelmuth** [comment]
@cloudchristina see https://github.com/open-telemetry/opentelemetry-collector/issues/10994#issuecomment-2326867397. The operator is the common factor, there is something weird happening when the operator does the install.

**Comment by TylerHelmuth** [comment]
But also in that screen shot it shows you are using the ADOT collector, which we are not in control of and cannot help with.
